<a href="https://colab.research.google.com/github/fernandonakagawa/ADS_5P_TE_Python_DS/blob/main/Aula_13_matplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercícios da Aula 12 - Numpy

In [32]:
# Crie um vetor nulo de tamanho 10

import numpy as np

array = np.empty(10)

array


array([0.0e+000, 4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323, 2.5e-323,
       3.0e-323, 3.5e-323, 4.0e-323, 4.4e-323])

In [33]:
# Como encontrar o tamanho da memória de qualquer matriz

print(array.size * array.itemsize)



80


In [6]:
# Crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1

array[4] = 1
array


array([2.29577839e-316, 3.60739284e-313, 1.38338381e-322, 2.29578472e-316,
       1.00000000e+000, 0.00000000e+000, 4.94065646e-323, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

In [7]:
# Crie um vetor com valores que variam de 10 a 49

array = np.random.randint(10, 50, size=10)
print(array)



[24 25 30 26 31 37 16 26 14 39]


In [8]:
# Inverter um vetor (o primeiro elemento se torna o último)

array = array[::-1]
print(array)




[39 14 26 16 37 31 26 30 25 24]


In [9]:
# Crie uma matriz 3x3 com valores que variam de 0 a 8

array = np.random.randint(0, 9, size=(3, 3))
print(array)



[[3 5 6]
 [1 0 4]
 [6 5 4]]


In [10]:
# Crie uma matriz de identidade 3x3

array = np.eye(3)
print(array)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# Crie uma matriz 3x3x3 com valores aleatórios

array = np.random.random(size=(3, 3, 3))
print(array)



[[[0.62084338 0.94612894 0.09613585]
  [0.85672552 0.56570734 0.80733547]
  [0.8568818  0.60575732 0.49338915]]

 [[0.87275849 0.46639701 0.87387316]
  [0.16727728 0.05900087 0.42930557]
  [0.42714276 0.56585516 0.83955207]]

 [[0.93202688 0.00499754 0.20213342]
  [0.02954423 0.94856071 0.91089347]
  [0.20124334 0.88307681 0.2914662 ]]]


In [12]:
# Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo e máximo

array = np.random.random(size=(10, 10))
print(array, 'max', array.max(), 'min', array.min())



[[0.75276803 0.9522984  0.64637027 0.27076685 0.85318554 0.85186636
  0.8134112  0.61618249 0.43702087 0.43273397]
 [0.65505878 0.22177113 0.96812694 0.62631056 0.32058249 0.04281359
  0.34062486 0.54248252 0.45787988 0.85026139]
 [0.47609547 0.74660921 0.95909815 0.07345205 0.92206337 0.43046731
  0.76429407 0.09906881 0.77933621 0.76156029]
 [0.57671853 0.77807565 0.36527424 0.2160459  0.83591074 0.41904351
  0.60014919 0.31301893 0.85852487 0.54708108]
 [0.00434515 0.17062379 0.79976632 0.84991072 0.97278842 0.57157117
  0.20782083 0.1380483  0.45442283 0.74947029]
 [0.72700168 0.18577108 0.68941071 0.48429602 0.31701013 0.21874623
  0.65516606 0.8823431  0.42607188 0.71462081]
 [0.76928564 0.42260341 0.83560083 0.7897768  0.2698188  0.87200417
  0.23784838 0.79398195 0.87618123 0.93900572]
 [0.44254407 0.74807763 0.591507   0.08463197 0.81283492 0.75473806
  0.25990276 0.13046411 0.40936461 0.12090729]
 [0.06189488 0.73275198 0.76840231 0.45449668 0.36720895 0.4892633
  0.19112748 

In [41]:
# Crie um vetor aleatório de tamanho 30 e encontre o valor médio

array = np.random.random(size=(30))
print(array, 'mean', array.mean())



[0.17847988 0.95739785 0.20775209 0.03301581 0.47780385 0.62810336
 0.15726872 0.9641763  0.85606079 0.50699553 0.8750472  0.42917424
 0.9850196  0.75240598 0.18058624 0.89233106 0.62557372 0.60866838
 0.12617652 0.76051127 0.060032   0.70252164 0.97908117 0.58006017
 0.63125646 0.8170527  0.02343705 0.20797844 0.81383159 0.19851574] mean 0.540543845176566


In [39]:
# Crie uma matriz 2D com 1 na borda e 0 dentro

array = np.zeros((10, 10))
array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1
print(array)




[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
# Crie uma matriz 5x5 com valores 1,2,3,4 logo abaixo da diagonal

array = np.eye(5)
for i in range(4):
    array[i + 1, i] = i + 1
print(array)




[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 2. 1. 0. 0.]
 [0. 0. 3. 1. 0.]
 [0. 0. 0. 4. 1.]]


In [17]:
# Crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b)

array = np.random.randint(0, 256, size=(8, 10, 3))
print(array)



[[[ 66 179 108]
  [ 43 101 106]
  [ 38 166  80]
  [ 57 245 203]
  [210  64 144]
  [ 16  78  41]
  [ 30  77 229]
  [184  80 115]
  [ 44 218  48]
  [ 29 192  90]]

 [[165 213   0]
  [ 24 252 221]
  [ 81  55  31]
  [124 246 134]
  [ 10 138  29]
  [154  22 215]
  [199 243 147]
  [164  24 193]
  [210 164 104]
  [ 87  44 120]]

 [[ 40 194  93]
  [ 26 148 234]
  [142 229 223]
  [109  44 166]
  [214 133 241]
  [201 192  91]
  [165 129 201]
  [105 240 219]
  [ 63   2  93]
  [ 99 219 153]]

 [[101  77 170]
  [196 186  28]
  [ 59 181 165]
  [167  62 178]
  [143 233 178]
  [216   2 199]
  [  9  11  29]
  [221  83 230]
  [ 91 149 161]
  [179  84  60]]

 [[224   4 189]
  [ 23 118 160]
  [ 29 163 217]
  [ 72 249  88]
  [203  75 164]
  [230  32 124]
  [ 89 253 204]
  [137  96 242]
  [ 15 253 127]
  [ 26 221 157]]

 [[184 144   2]
  [226 240 135]
  [149 116   2]
  [215  98 214]
  [166  22 100]
  [251 130 139]
  [140 154 113]
  [ 29  26  14]
  [ 41  61  99]
  [ 77 229 167]]

 [[204 196  79]
  [111 238 1

In [49]:
mat = np.zeros([3,3])
for i in range(3):
  for j in range(3):
    texto = f"Digite o número {i}, {j}: "
    mat[i][j] = input(texto)
print(mat)


Digite o número 0, 0: 1
Digite o número 0, 1: 2
Digite o número 0, 2: 3
Digite o número 1, 0: 4
Digite o número 1, 1: 5
Digite o número 1, 2: 6
Digite o número 2, 0: 7
Digite o número 2, 1: 8
Digite o número 2, 2: 9
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [55]:
mat = np.add(mat, [10,20,30])
print(mat)

[[21. 42. 63.]
 [24. 45. 66.]
 [27. 48. 69.]]


In [57]:
mat = np.append(mat, [10,20,30])
mat

array([21., 42., 63., 24., 45., 66., 27., 48., 69., 10., 20., 30., 10.,
       20., 30.])

In [22]:
# Subtrair a média de cada linha de uma matriz
array = np.random.random(size=(3, 3))
mean = array.mean(axis=1)
#mean = np.expand_dims(mean, axis=1)
print(array)
print(mean)
print(array - mean)




[[0.11580243 0.05244782 0.34257467]
 [0.89964472 0.76617984 0.80557382]
 [0.14839569 0.2653365  0.17957325]]
[0.17027497 0.82379946 0.19776848]
[[-0.05447254 -0.77135165  0.14480619]
 [ 0.72936975 -0.05761962  0.60780534]
 [-0.02187928 -0.55846296 -0.01819523]]


In [59]:
mat1 = np.eye(3)
print(mat1)
mat2 = np.random.randint(0, 9, size=(3, 3))
print(mat2)
print(mat1 + mat2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[8 8 0]
 [1 2 4]
 [4 4 4]]
[[9. 8. 0.]
 [1. 3. 4.]
 [4. 4. 5.]]


In [61]:
# Como encontrar o valor mais frequente em uma matriz?

from scipy import stats
from numpy import random
array = random.choice([3, 5, 7, 9], p=[0.1, 0.2, 0.6, 0.1], size=(100))
print(array)
print(stats.mode(array.flatten()))



[7 7 5 3 9 7 5 7 5 7 7 7 5 5 7 7 7 5 7 7 7 5 5 7 7 7 9 7 7 5 3 7 7 7 5 5 7
 7 5 7 7 7 5 7 7 5 7 7 9 7 7 7 5 5 7 7 5 7 7 7 7 3 7 7 7 7 7 9 9 7 5 9 7 5
 7 7 3 7 7 7 7 5 5 5 5 7 3 3 7 7 7 9 7 7 7 3 7 5 7 9]
ModeResult(mode=array([7]), count=array([61]))


In [29]:
# Crie uma matriz a partir de um arquivo
#array = np.load('matriz.npy')
#print(array)
   # StringIO se comporta como um arquivo
from io import StringIO
c = StringIO("0 1\n2 3")
np.loadtxt(c)




array([[0., 1.],
       [2., 3.]])

In [64]:
mat = np.loadtxt("matriz.txt")
print(mat)
print(mat + 5)

[[0. 1.]
 [2. 3.]]
[[5. 6.]
 [7. 8.]]


In [67]:
# crie uma matriz com valores aletaórios e salve para um arquivo

array = np.random.randint(0, 256, size=(8, 10, 3))
np.save('matriz2.txt', array)
print(array)

[[[188   3  72]
  [ 74  35 160]
  [165 193 151]
  [  2  25 218]
  [ 45 134 103]
  [219 102 233]
  [158  60 246]
  [ 17 163 131]
  [126 133 232]
  [219 212 164]]

 [[150  97 201]
  [ 19 181 221]
  [ 25 178 243]
  [253 105 105]
  [145 128  23]
  [ 66 106 104]
  [ 83  38 202]
  [196  11  60]
  [235  52 210]
  [ 12 221 126]]

 [[ 88  56  51]
  [ 36 133 156]
  [155 151 252]
  [229 254 127]
  [ 51 121 244]
  [205 131   3]
  [ 65 249 223]
  [226  25 228]
  [146  18 168]
  [ 27 156  61]]

 [[199 225 190]
  [186 217 212]
  [ 40  86  75]
  [ 70 155  97]
  [149   6   5]
  [ 85  55  52]
  [ 54  30  77]
  [ 76 132  80]
  [205 152 172]
  [225 102 114]]

 [[ 10 196 210]
  [152 162  30]
  [126 210  78]
  [128 153 195]
  [205  82  77]
  [ 97 233 127]
  [204 154 212]
  [ 85   4 123]
  [ 90  67 251]
  [204 240 205]]

 [[235   0 173]
  [221 139 159]
  [106  92 100]
  [239 249 139]
  [158 168 194]
  [243  31  10]
  [172   3 130]
  [204 187  68]
  [ 13 242 152]
  [111 251 245]]

 [[ 46 249  53]
  [212  27 1

In [69]:
np.savetxt('matriz3.txt', mat2)