<a href="https://colab.research.google.com/github/fernandonakagawa/ADS_5P_TE_Python_DS/blob/main/Aula_13_matplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercícios da Aula 12 - Numpy

In [3]:
# Crie um vetor nulo de tamanho 10

import numpy as np

array = np.empty(10)

array


array([2.29577839e-316, 3.60739284e-313, 1.38338381e-322, 2.29578472e-316,
       0.00000000e+000, 0.00000000e+000, 4.94065646e-323, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

In [4]:
# Como encontrar o tamanho da memória de qualquer matriz

print(array.size * array.itemsize)



80


In [6]:
# Crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1

array[4] = 1
array


array([2.29577839e-316, 3.60739284e-313, 1.38338381e-322, 2.29578472e-316,
       1.00000000e+000, 0.00000000e+000, 4.94065646e-323, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

In [7]:
# Crie um vetor com valores que variam de 10 a 49

array = np.random.randint(10, 50, size=10)
print(array)



[24 25 30 26 31 37 16 26 14 39]


In [8]:
# Inverter um vetor (o primeiro elemento se torna o último)

array = array[::-1]
print(array)




[39 14 26 16 37 31 26 30 25 24]


In [9]:
# Crie uma matriz 3x3 com valores que variam de 0 a 8

array = np.random.randint(0, 9, size=(3, 3))
print(array)



[[3 5 6]
 [1 0 4]
 [6 5 4]]


In [10]:
# Crie uma matriz de identidade 3x3

array = np.eye(3)
print(array)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# Crie uma matriz 3x3x3 com valores aleatórios

array = np.random.random(size=(3, 3, 3))
print(array)



[[[0.62084338 0.94612894 0.09613585]
  [0.85672552 0.56570734 0.80733547]
  [0.8568818  0.60575732 0.49338915]]

 [[0.87275849 0.46639701 0.87387316]
  [0.16727728 0.05900087 0.42930557]
  [0.42714276 0.56585516 0.83955207]]

 [[0.93202688 0.00499754 0.20213342]
  [0.02954423 0.94856071 0.91089347]
  [0.20124334 0.88307681 0.2914662 ]]]


In [12]:
# Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo e máximo

array = np.random.random(size=(10, 10))
print(array, 'max', array.max(), 'min', array.min())



[[0.75276803 0.9522984  0.64637027 0.27076685 0.85318554 0.85186636
  0.8134112  0.61618249 0.43702087 0.43273397]
 [0.65505878 0.22177113 0.96812694 0.62631056 0.32058249 0.04281359
  0.34062486 0.54248252 0.45787988 0.85026139]
 [0.47609547 0.74660921 0.95909815 0.07345205 0.92206337 0.43046731
  0.76429407 0.09906881 0.77933621 0.76156029]
 [0.57671853 0.77807565 0.36527424 0.2160459  0.83591074 0.41904351
  0.60014919 0.31301893 0.85852487 0.54708108]
 [0.00434515 0.17062379 0.79976632 0.84991072 0.97278842 0.57157117
  0.20782083 0.1380483  0.45442283 0.74947029]
 [0.72700168 0.18577108 0.68941071 0.48429602 0.31701013 0.21874623
  0.65516606 0.8823431  0.42607188 0.71462081]
 [0.76928564 0.42260341 0.83560083 0.7897768  0.2698188  0.87200417
  0.23784838 0.79398195 0.87618123 0.93900572]
 [0.44254407 0.74807763 0.591507   0.08463197 0.81283492 0.75473806
  0.25990276 0.13046411 0.40936461 0.12090729]
 [0.06189488 0.73275198 0.76840231 0.45449668 0.36720895 0.4892633
  0.19112748 

In [14]:
# Crie um vetor aleatório de tamanho 30 e encontre o valor médio

array = np.random.random(size=(30))
print(array, 'mean', array.mean())



[0.64808492 0.10206147 0.2406878  0.35675297 0.80901256 0.96702566
 0.31834648 0.46578345 0.2331084  0.38160468 0.94394413 0.82850148
 0.19591661 0.85955393 0.66435571 0.96353247 0.07950312 0.12162634
 0.23931409 0.25698562 0.44905334 0.64442905 0.5970005  0.44824341
 0.50203184 0.36091706 0.54601145 0.61354523 0.914263   0.59042263] mean 0.5113873131620394


In [15]:
# Crie uma matriz 2D com 1 na borda e 0 dentro

array = np.zeros((10, 10))
array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1
print(array)




[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
# Crie uma matriz 5x5 com valores 1,2,3,4 logo abaixo da diagonal

array = np.eye(5)
for i in range(4):
    array[i + 1, i] = i + 1
print(array)




[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 2. 1. 0. 0.]
 [0. 0. 3. 1. 0.]
 [0. 0. 0. 4. 1.]]


In [17]:
# Crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b)

array = np.random.randint(0, 256, size=(8, 10, 3))
print(array)



[[[ 66 179 108]
  [ 43 101 106]
  [ 38 166  80]
  [ 57 245 203]
  [210  64 144]
  [ 16  78  41]
  [ 30  77 229]
  [184  80 115]
  [ 44 218  48]
  [ 29 192  90]]

 [[165 213   0]
  [ 24 252 221]
  [ 81  55  31]
  [124 246 134]
  [ 10 138  29]
  [154  22 215]
  [199 243 147]
  [164  24 193]
  [210 164 104]
  [ 87  44 120]]

 [[ 40 194  93]
  [ 26 148 234]
  [142 229 223]
  [109  44 166]
  [214 133 241]
  [201 192  91]
  [165 129 201]
  [105 240 219]
  [ 63   2  93]
  [ 99 219 153]]

 [[101  77 170]
  [196 186  28]
  [ 59 181 165]
  [167  62 178]
  [143 233 178]
  [216   2 199]
  [  9  11  29]
  [221  83 230]
  [ 91 149 161]
  [179  84  60]]

 [[224   4 189]
  [ 23 118 160]
  [ 29 163 217]
  [ 72 249  88]
  [203  75 164]
  [230  32 124]
  [ 89 253 204]
  [137  96 242]
  [ 15 253 127]
  [ 26 221 157]]

 [[184 144   2]
  [226 240 135]
  [149 116   2]
  [215  98 214]
  [166  22 100]
  [251 130 139]
  [140 154 113]
  [ 29  26  14]
  [ 41  61  99]
  [ 77 229 167]]

 [[204 196  79]
  [111 238 1

In [22]:
# Subtrair a média de cada linha de uma matriz
array = np.random.random(size=(3, 3))
mean = array.mean(axis=1)
#mean = np.expand_dims(mean, axis=1)
print(array)
print(mean)
print(array - mean)




[[0.11580243 0.05244782 0.34257467]
 [0.89964472 0.76617984 0.80557382]
 [0.14839569 0.2653365  0.17957325]]
[0.17027497 0.82379946 0.19776848]
[[-0.05447254 -0.77135165  0.14480619]
 [ 0.72936975 -0.05761962  0.60780534]
 [-0.02187928 -0.55846296 -0.01819523]]


In [27]:
# Como encontrar o valor mais frequente em uma matriz?

from scipy import stats
from numpy import random
array = random.choice([3, 5, 7, 9], p=[0.1, 0.5, 0.3, 0.1], size=(100))
print(array)
print(stats.mode(array.flatten()))



[5 7 5 5 5 3 5 5 5 7 7 7 3 7 5 5 5 5 7 5 3 9 7 5 3 5 7 7 5 5 5 7 7 7 7 5 9
 5 7 9 5 5 5 7 5 5 7 5 7 5 7 7 7 9 5 5 7 5 5 5 7 5 5 5 3 9 7 5 5 7 7 3 5 9
 7 7 5 7 5 3 9 5 7 3 5 7 7 5 3 7 7 5 5 5 7 9 5 5 7 5]
ModeResult(mode=array([5]), count=array([48]))


In [29]:
# Crie uma matriz a partir de um arquivo
#array = np.load('matriz.npy')
#print(array)

from io import StringIO   # StringIO se comporta como um arquivo
c = StringIO("0 1\n2 3")
np.loadtxt(c)




array([[0., 1.],
       [2., 3.]])

In [30]:
# crie uma matriz com valores aletaórios e salve para um arquivo

array = np.random.randint(0, 256, size=(8, 10, 3))
np.save('matriz', array)
print(array)

[[[ 70 212   3]
  [156 115  60]
  [218   5 217]
  [ 39 238 131]
  [203 168 206]
  [ 40  64  89]
  [ 72 165 203]
  [217 164 198]
  [208 175  16]
  [ 83 191 145]]

 [[ 82 131 203]
  [146 151 176]
  [104 213 204]
  [236 236  19]
  [ 90 149 152]
  [ 51 246 160]
  [249 194 206]
  [ 72   9  86]
  [141 192  60]
  [212 165  42]]

 [[115  56  91]
  [172 182  45]
  [188 102  58]
  [ 10  99  48]
  [245  20 172]
  [238 240 233]
  [247  19  64]
  [ 97  89  24]
  [ 13 206  99]
  [170 148 140]]

 [[206 114 174]
  [ 24 244 117]
  [  9 212 220]
  [ 39 240 107]
  [ 98 156  34]
  [ 11  37  29]
  [180 209 233]
  [ 95 184  26]
  [ 65 106 206]
  [164  48 251]]

 [[ 77  55 236]
  [131  58 112]
  [227 191 119]
  [112  11 146]
  [ 26 146  98]
  [195 239 213]
  [226 216  24]
  [132 214 252]
  [186  52 232]
  [ 17  57 186]]

 [[111 110 131]
  [233 221 220]
  [196  93 138]
  [178 107  25]
  [240  75 105]
  [246 251  99]
  [ 35 148  93]
  [106 248   3]
  [ 94  21 198]
  [ 69  36 244]]

 [[ 24 179  65]
  [ 89 198 1